services:
  backend:
    build:
      context: ./src/backend/
      dockerfile: dev.Dockerfile
      additional_contexts:
        ocelescope: ./src/ocelescope
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - plugins_store:/plugins
    environment:
      - DATA_DIR=/app/data
      - PLUGIN_DIR=/plugins 
    develop:
      watch:
        - action: sync+restart
          path: ./src/backend
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path:  ./src/backend/uv.lock
  frontend:
      build:
        context: ./src/frontend
        dockerfile: dev.Dockerfile  
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=development
      develop:
        watch:
          - action: sync
            path: ./src/frontend
            target: /app
            ignore:
              - node_modules/
              - .next/
          - action: rebuild
            path: ./src/frontend/package-lock.json

volumes:
  plugins_store:
