services:
  backend:
    build:
      context: ./src/backend/
      dockerfile: dev.Dockerfile
      additional_contexts:
        ocelescope: ./src/ocelescope
    volumes:
      - ./data:/app/data
      - plugins_store:/plugins
    environment:
      - DATA_DIR=/app/data
      - PLUGIN_DIR=/plugins
    develop:
      watch:
        - action: sync
          path: ./src/backend
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./src/backend/uv.lock
  frontend:
    build:
      context: ./src/newFrontend/
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./src/newFrontend/
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./src/newFrontend/package-lock.json

volumes:
  plugins_store:
