title: Ocelescope
description: An Extensible Web Framework for Object-Centric Event Logs  
theme: just-the-docs

url: https://rwth-pads.github.io/ocelescope

aux_links:
  Template Repository: https://github.com/rwth-pads/ocelescope
