services:
  backend:
    image: grkmr/ocelescope_backend:latest
    ports:
      - "8000:8000"
    volumes:
      - plugins_store:/plugins
    restart: unless-stopped

  frontend:
    image: grkmr/ocelescope_frontend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  plugins_store:
