services:
  backend:
    image: ghcr.io/rwth-pads/ocelescope-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - plugins_store:/plugins
    restart: unless-stopped

  frontend:
    image: ghcr.io/rwth-pads/ocelescope-frontend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  plugins_store:
